-- A script to set up a database.
-- WILL BE CHANGED AND WILL NOT INCLUDE MIGRATION CODE
USE autobak;

CREATE TABLE user (
	id BIGINT UNSIGNED NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(80) NOT NULL UNIQUE,
	password CHAR(73) NOT NULL,
	is_superuser SET('Y', 'N') NOT NULL DEFAULT 'N'
);

CREATE TABLE audit (
	id BIGINT UNSIGNED NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
	user BIGINT UNSIGNED NULL DEFAULT NULL,
	time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	address INT(32) UNSIGNED NOT NULL,
	event SET('AUTH', 'NEW_STASH', 'DELETE_STASH', 'LIST', 'DOWNLOAD', 'UPLOAD', 'DELETE_FILE') NOT NULL,
	success SET('Y', 'N') NOT NULL,
	info TEXT NULL DEFAULT NULL,

	CONSTRAINT FOREIGN KEY (user) REFERENCES user(id)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);

CREATE TABLE stash (
	id BIGINT UNSIGNED NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
	owner BIGINT UNSIGNED NOT NULL,
	name VARCHAR(80) NOT NULL,

	UNIQUE (owner, name),
	CONSTRAINT FOREIGN KEY (owner) REFERENCES user(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE file (
	id BIGINT UNSIGNED NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
	stash BIGINT UNSIGNED NOT NULL,
	name VARCHAR(256) NOT NULL,
	update_time BIGINT UNSIGNED NOT NULL,

	UNIQUE (stash, name),
	CONSTRAINT FOREIGN KEY (stash) REFERENCES stash(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
