-- A script to set up a database.
-- WILL BE CHANGED AND WILL NOT INCLUDE MIGRATION CODE
USE autobak;

CREATE TABLE user (
	id INT(64) UNSIGNED NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(80) NOT NULL UNIQUE,
	password CHAR(73) NOT NULL,
	is_superuser SET('Y', 'N') NOT NULL DEFAULT 'N'
);

CREATE TABLE audit (
	id INT(64) UNSIGNED NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
	user INT(64) UNSIGNED NULL DEFAULT NULL,
	time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	address INT(32) UNSIGNED NOT NULL,
	event SET('AUTH') NOT NULL,
	success SET('Y', 'N') NOT NULL,

	CONSTRAINT FOREIGN KEY (user) REFERENCES user(id)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);
